# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'disrupt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '10.0'

  # Pods for disrupt
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'YelpAPI', '~> 2.0'
  pod 'BrightFutures', '~> 5.1'
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON', '3.0.0'
  

  target 'disruptTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'disruptUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
